/*6 задание*/

CREATE SEQUENCE seq_caterer
    START WITH 1
    INCREMENT BY 1;
CREATE SEQUENCE seq_deliver
  	START WITH 1
  	INCREMENT BY 1;
CREATE SEQUENCE seq_employer
    START WITH 1
    INCREMENT BY 1;
CREATE SEQUENCE seq_messure
    START WITH 1
    INCREMENT BY 1;
CREATE SEQUENCE seq_section
    START WITH 1
    INCREMENT BY 1;
CREATE SEQUENCE seq_material
    START WITH 1
    INCREMENT BY 1;
CREATE SEQUENCE seq_supply
    START WITH 1
    INCREMENT BY 1;
CREATE SEQUENCE seq_surplus
    START WITH 1
    INCREMENT BY 1;
CREATE SEQUENCE seq_store
    START WITH 1
    INCREMENT BY 1;
CREATE SEQUENCE seq_group
    START WITH 1
    INCREMENT BY 1;
CREATE SEQUENCE seq_inprice
    START WITH 1
    INCREMENT BY 1;

/*7 задание*/

INSERT INTO T_MESSURE (ID_MESSURE, NAME)
  VALUES (SEQ_MESSURE.NEXTVAL, 'ШТ');
INSERT INTO T_MESSURE (ID_MESSURE, NAME)
  VALUES (SEQ_MESSURE.NEXTVAL, 'М');
INSERT INTO T_MESSURE (ID_MESSURE, NAME)
  VALUES (SEQ_MESSURE.NEXTVAL, 'КГ');
INSERT INTO T_MESSURE (ID_MESSURE, NAME)
  VALUES (SEQ_MESSURE.NEXTVAL, 'МЛ');
INSERT INTO T_MESSURE (ID_MESSURE, NAME)
  VALUES (SEQ_MESSURE.NEXTVAL, 'ГР');

INSERT INTO T_GROUP (ID_GROUP, NAME)
  VALUES (SEQ_GROUP.NEXTVAL, 'Группа 1');
INSERT INTO T_GROUP (ID_GROUP, NAME)
  VALUES (SEQ_GROUP.NEXTVAL, 'Группа 2');
INSERT INTO T_GROUP (ID_GROUP, NAME)
  VALUES (SEQ_GROUP.NEXTVAL, 'Группа 3');
INSERT INTO T_GROUP (ID_GROUP, NAME)
  VALUES (SEQ_GROUP.NEXTVAL, 'Группа 4');
INSERT INTO T_GROUP (ID_GROUP, NAME)
  VALUES (SEQ_GROUP.NEXTVAL, 'Группа 5');

INSERT INTO T_MATERIAL (ID_MATERIAL, NAME, ID_MESSURE, ID_GROUP)
  VALUES (SEQ_MATERIAL.NEXTVAL, 'Материал 1', 1, 1);
INSERT INTO T_MATERIAL (ID_MATERIAL, NAME, ID_MESSURE, ID_GROUP)
  VALUES (SEQ_MATERIAL.NEXTVAL, 'Материал 2', 2, 2);
INSERT INTO T_MATERIAL (ID_MATERIAL, NAME, ID_MESSURE, ID_GROUP)
  VALUES (SEQ_MATERIAL.NEXTVAL, 'Материал 3', 3, 3);
INSERT INTO T_MATERIAL (ID_MATERIAL, NAME, ID_MESSURE, ID_GROUP)
  VALUES (SEQ_MATERIAL.NEXTVAL, 'Материал 4', 4, 4);
INSERT INTO T_MATERIAL (ID_MATERIAL, NAME, ID_MESSURE, ID_GROUP)
  VALUES (SEQ_MATERIAL.NEXTVAL, 'Материал 5', 5, 5);

INSERT INTO T_CATERER (ID_CATERER, NAME, PHONE, OBHI_ADDRES, FIZ_ADDERS, E_MAIL,FAX)
  VALUES (SEQ_CATERER.NEXTVAL, 'Поставщик 1', 89033454556,'Страна,город, улица, дом', 'Город, улица, дом', '214_1@mail.ru',NULL);
INSERT INTO T_CATERER (ID_CATERER, NAME, PHONE, OBHI_ADDRES, FIZ_ADDERS, E_MAIL,FAX)
  VALUES (SEQ_CATERER.NEXTVAL, 'Поставщик 2', 89224375690, NULL, 'Страна,город, улица, дом', 'Город, улица, дом', '214_2@mail.ru',NULL);
INSERT INTO T_CATERER (ID_CATERER, NAME, PHONE, OBHI_ADDRES, FIZ_ADDERS, E_MAIL,FAX)
  VALUES (SEQ_CATERER.NEXTVAL, 'Поставщик 3', 89224673538, NULL, 'Страна,город, улица, дом', 'Город, улица, дом', '214_3@mail.ru',NULL);
INSERT INTO T_CATERER (ID_CATERER, NAME, PHONE, OBHI_ADDRES, FIZ_ADDERS, E_MAIL,FAX)
  VALUES (SEQ_CATERER.NEXTVAL, 'Поставщик 4', 89193627464, NULL, 'Страна,город, улица, дом', 'Город, улица, дом', '214_4@mail.ru',NULL);
INSERT INTO T_CATERER (ID_CATERER, NAME, PHONE, OBHI_ADDRES, FIZ_ADDERS, E_MAIL, FAX)
  VALUES (SEQ_CATERER.NEXTVAL, 'Поставщик 5', 89094364354, NULL, 'Страна,город, улица, дом', 'Город, улица, дом', '214_5@mail.ru',NULL);

INSERT INTO T_STORE (ID_STORE, NAME)
  VALUES (SEQ_STORE.NEXTVAL, 'Склад 1');
INSERT INTO T_STORE (ID_STORE, NAME)
  VALUES (SEQ_STORE.NEXTVAL, 'Склад 2');
INSERT INTO T_STORE (ID_STORE, NAME)
  VALUES (SEQ_STORE.NEXTVAL, 'Склад 3');
INSERT INTO T_STORE (ID_STORE, NAME)
  VALUES (SEQ_STORE.NEXTVAL, 'Склад 4');
INSERT INTO T_STORE (ID_STORE, NAME)
  VALUES (SEQ_STORE.NEXTVAL, 'Склад 5');
  
INSERT INTO T_SURPLUS (ID_MATERIAL, ID_STORE, VOLUME)
  VALUES (1, 1, 1);
INSERT INTO T_SURPLUS (ID_MATERIAL, ID_STORE, VOLUME)
  VALUES (2, 2, 2);
INSERT INTO T_SURPLUS (ID_MATERIAL, ID_STORE, VOLUME)
  VALUES (3, 3, 3);
INSERT INTO T_SURPLUS (ID_MATERIAL, ID_STORE, VOLUME)
  VALUES (4, 4, 4);
INSERT INTO T_SURPLUS (ID_MATERIAL, ID_STORE, VOLUME)
  VALUES (5, 5, 5);

INSERT INTO T_EMPLOYER (ID_EMPLOYER, SURNAME, NAME, FATHER_NAME)
  VALUES (SEQ_EMPLOYER.NEXTVAL, 'Фамилия', 'Имя', 'Отчество');
INSERT INTO T_EMPLOYER (ID_EMPLOYER, SURNAME, NAME, FATHER_NAME)
  VALUES (SEQ_EMPLOYER.NEXTVAL, 'Фамилия', 'Имя', 'Отчество');
INSERT INTO T_EMPLOYER (ID_EMPLOYER, SURNAME, Name, FATHER_NAME)
  VALUES (SEQ_EMPLOYER.NEXTVAL, 'Фамилия', 'Имя', 'Отчество');
INSERT INTO T_EMPLOYER (ID_EMPLOYER, SURNAME, Name, FATHER_NAME)
  VALUES (SEQ_EMPLOYER.NEXTVAL, 'Фамилия', 'Имя', 'Отчество');
INSERT INTO T_EMPLOYER (ID_EMPLOYER, SURNAME, Name, FATHER_NAME)
  VALUES (SEQ_EMPLOYER.NEXTVAL, 'Фамилия', 'Имя', 'Отчество');

INSERT INTO T_SECTION (ID_SECTION, NAME, ID_EMPLOYER)
  VALUES (SEQ_SECTION.NEXTVAL, 'Цех 1', 1);
INSERT INTO T_SECTION (ID_SECTION, NAME, ID_EMPLOYER)
  VALUES (SEQ_SECTION.NEXTVAL, 'Цех 2', 2);
INSERT INTO T_SECTION (ID_SECTION, NAME, ID_EMPLOYER)
  VALUES (SEQ_SECTION.NEXTVAL, 'Цех 3', 3);
INSERT INTO T_SECTION (ID_SECTION, NAME, ID_EMPLOYER)
  VALUES (SEQ_SECTION.NEXTVAL, 'Цех 4', 4);
INSERT INTO T_SECTION (ID_SECTION, NAME, ID_EMPLOYER)
  VALUES (SEQ_SECTION.NEXTVAL, 'Цех 4', 5);

INSERT INTO T_DELIVER (ID_DELIVER, ID_SECTION, ID_MATERIAL, ID_STORE, DELIVER_DATE)
  VALUES (SEQ_DELIVER.NEXTVAL, 1, 1, 1, '17.04.2017');
INSERT INTO T_DELIVER (ID_DELIVER, ID_SECTION, ID_MATERIAL, ID_STORE, DELIVER_DATE)
  VALUES (SEQ_DELIVER.NEXTVAL, 2, 2, 2, '18.04.2017');
INSERT INTO T_DELIVER (ID_DELIVER, ID_SECTION, ID_MATERIAL, ID_STORE, DELIVER_DATE)
  VALUES (SEQ_DELIVER.NEXTVAL, 3, 3, 3, '19.04.2017');
INSERT INTO T_DELIVER (ID_DELIVER, ID_SECTION, ID_MATERIAL, ID_STORE, DELIVER_DATE)
  VALUES (SEQ_DELIVER.NEXTVAL, 4, 4, 4, '20.04.2017');
INSERT INTO T_DELIVER (ID_DELIVER, ID_SECTION, ID_MATERIAL, ID_STORE, DELIVER_DATE)
  VALUES (SEQ_DELIVER.NEXTVAL, 5, 5, 5, '21.04.2017);

INSERT INTO T_INPRICE (ID_MATERIAL, PRICE_DATE, PRICE)
  VALUES (SEQ_INPRICE.NEXTVAL, '17.04.2017', 1);
INSERT INTO T_INPRICE (ID_MATERIAL, PRICE_DATE, PRICE)
  VALUES (SEQ_INPRICE.NEXTVAL, '18.04.2017', 2);
INSERT INTO T_INPRICE (ID_MATERIAL, PRICE_DATE, PRICE)
  VALUES (SEQ_INPRICE.NEXTVAL, '19.04.2017', 3);
INSERT INTO T_INPRICE (ID_MATERIAL, PRICE_DATE, PRICE)
  VALUES (SEQ_INPRICE.NEXTVAL, '20.04.2017', 4);
INSERT INTO T_INPRICE (ID_MATERIAL, PRICE_DATE, PRICE)
  VALUES (SEQ_INPRICE.NEXTVAL, '21.04.2017', 5);

INSERT INTO T_SUPPLY (ID_SUPPLY, ID_CATERER, ID_MATERIAL, ID_STORE, SUPPLY_DATE, VOLUME)
  VALUES (SEQ_SUPPLY.NEXTVAL, 1, 1, 1, '17.04.2017', 1);
INSERT INTO T_SUPPLY (ID_SUPPLY, ID_CATERER, ID_MATERIAL, ID_STORE, SUPPLY_DATE, VOLUME)
  VALUES (SEQ_SUPPLY.NEXTVAL, 2, 2, 2, '18.04.2017', 2);
INSERT INTO T_SUPPLY (ID_SUPPLY, ID_CATERER, ID_MATERIAL, ID_STORE, SUPPLY_DATE, VOLUME)
  VALUES (SEQ_SUPPLY.NEXTVAL, 3, 3, 3, '19.04.2017', 3);
INSERT INTO T_SUPPLY (ID_SUPPLY, ID_CATERER, ID_MATERIAL, ID_STORE, SUPPLY_DATE, VOLUME)
  VALUES (SEQ_SUPPLY.NEXTVAL, 4, 4, 4, '20.04.2017', 4);
INSERT INTO T_SUPPLY (ID_SUPPLY, ID_CATERER, ID_MATERIAL, ID_STORE, SUPPLY_DATE, VOLUME)
  VALUES (SEQ_SUPPLY.NEXTVAL, 5, 5, 5, '21.04.2017', 5);

/*8 задание*/

DELETE FROM T_INPRICE
  WHERE PRICE_DATE < '31.12.2000';

/*9 задание*/

DELETE FROM T_MESSURE
  WHERE NAME LIKE '_';

/*10 задание*/

 UPDATE T_SURPLUS 
 SET VOLUME = 0
  WHERE ID_STORE LIKE 2;

/*11 задание*/

UPDATE T_EMPLOYER
SET SURNAME = 'Акманаева'
   WHERE ID_EMPLOYER LIKE 4;

/*12 задание*/

UPDATE T_CATERER
  SET PHONE = 89922067549
    WHERE NAME LIKE 'Поставщик 1';


/*13 задание*/

UPDATE T_INPRICE 
  SET PRICE = 0.85 * PRICE
    WHERE PRICE_DATE LIKE '%2017%'
